import axios from "axios";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useEffect } from "react";
import { getJWT } from "../../utils/jwtUtils";

interface Props {
  title: string;
  protectedRoute?: boolean;
  forwardAuthenticated?: boolean;
}

function AppHead({
  title,
  protectedRoute = false,
  forwardAuthenticated = false,
}: Props) {
  const router = useRouter();

  axios.defaults.baseURL = "http://localhost:1337/api";

  useEffect(() => {
    if (protectedRoute && !getJWT()) {
      router.push("/login");
    }

    if (forwardAuthenticated && getJWT()) {
      router.push("/");
    }
  }, [forwardAuthenticated, protectedRoute, router]);

  return (
    <>
      <ToastContainer />
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export default AppHead;
